#!/bin/sh

apt-get update
sudo apt-get install unzip make gcc openssl pkg-config libavahi-client-dev libasound2-dev libpulse-­dev build-essential mesa-utils libao-common libcrypt-openssl-rsa-perl libao-dev libio-socket-inet6-perl libwww-perl avahi-utils  libshairport1 libshairport-dev libasound2-doc libglib2.0-doc -y
apt-get autoremove -y
sudo apt-get install libssl-dev -y
apt-get update

cd ~/Documents

mkdir shairport

cd shairport

#Stabile:
wget https://github.com/abrasive/shairport/archive/master.zip
#Alternative, correct below:
#wget https://github.com/abrasive/shairport/archive/1.0-dev.zip

unzip master.zip

rm master.zip

cd ~/Desktop

#Create a .sh file on the Desktop to run Airplay
touch run_shairport.sh

cd ~/Documents/shairport/shairport-master
./configure
sudo make
sudo make install 

cd ~/Desktop
echo "
#!/bin/bash
cd ~/Documents/shairport/shairport-master
./shairport -a 'Shairport' -d

read
" >> run_shairport.sh

#remove lock
chmod +x run_shairport.sh

bash run_shairport.sh
